 # jupyter
 ## markdown


In [2]:
import numpy as np

## 创建数组

In [3]:
arr1 = np.arange(15).reshape(3,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 常用属性

In [5]:
print(arr1.ndim) #维度
print(arr1.shape) #描述行列式
print(arr1.size) # 描述大小
print(arr1.dtype) # 描述类型 int64 (需要复习)
print(arr1.itemsize) # 元素大小
print(type(arr1))  #类型

print(np.array([1, 2], dtype='int32').itemsize)

2
(3, 5)
15
int64
8
<class 'numpy.ndarray'>
4


### array()  python列表转ndarray

In [ ]:
my_list = [7,8,9,4,5,6,1,23]

# 把python中的列表转numpy的ndarray
arr2 = np.array(my_list)
print(arr2)
print(type(arr2))

### arange 创建ndarray对象

In [8]:
# arange(起始, 结束, 步长, dtype = 类型)
arr3 = np.arange(0, 10, 2,dtype=int)
print(arr3)
print(type(arr3))
print(arr3.dtype)

[0 2 4 6 8]
<class 'numpy.ndarray'>
int64


### 随机数生成 ndarray

In [9]:
# random.rand()  生成 [0,1)之间 左闭右开的小数矩阵
arr4 = np.random.rand(3, 5)
print(arr4)

[[0.11006089 0.0324807  0.54177644 0.68543113 0.84760192]
 [0.63545706 0.46345836 0.09803476 0.71697399 0.99798979]
 [0.50575048 0.2681988  0.10205019 0.07814885 0.60904175]]


In [ ]:
# random.randint(起始, 结束, size=(行,列)) 生成指定范围 左闭右开 的随机整数矩阵
arr5 = np.random.randint(-5, 10, size=(3,4))
print(arr5)

In [10]:
# random.uniform(起始, 结束, size=(行,列)) 生成指定范围 左闭右开 的随机小数矩阵
arr6 = np.random.uniform(-5, 10, size=(3,4))
print(arr6)

[[-2.06273639  0.88615515  2.27519027 -4.07826017]
 [ 8.90441394 -2.67732091  6.22477506  9.47437581]
 [ 4.03203961 -0.60137078  9.75242198 -4.59691534]]


### numpy类型转换 astype()

In [11]:
arr7 = np.arange(0, 10, 2)
print(arr7)
arr8 = arr7.astype(np.float64)
print(arr8)
print(arr8.dtype)

[0 2 4 6 8]
[0. 2. 4. 6. 8.]
float64


### 等比/等差数列

In [14]:
# np.logspace 等比数列
# np.logspace(0,10,10) 开始 和 结束是10的幂次方(默认底数是10) 闭区间 元素个数为10
# np.logspace(0,0,10,base=2) 底数为2
a = np.logspace(0,9,10)
print(a)
aa = np.logspace(0,3,4,base=2)
print(aa)

# np.linspace 等差数列
# np.linspace(1,10,10,endpoint=True) 开始,结束,元素个数  闭区间
#                     endpoint(默认为True 右闭区间)
b = np.linspace(1,10,10,endpoint=False)
print(b)


[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
[1. 2. 4. 8.]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


# numpy常用函数

### 基本函数

In [87]:
# 创建正态分布标准序列
arr10 = np.random.randn(3,5) # 生成(−∞,+∞)之间的3行5列矩阵
print(arr10)

[[-2.05350225 -1.30746331  1.26118858  0.47843432  1.16760753]
 [ 0.40092568  1.34853534  0.8970547  -0.98781217 -0.79653315]
 [ 0.38773733 -3.25536926  0.55567805  0.74809271 -0.83242683]]


In [97]:
# 基本函数
print(np.ceil(arr10)) # 向上取整
print(np.floor(arr10)) # 向下取整
print(np.rint(arr10)) # 四舍五入
print(np.abs(arr10)) # 绝对值
# 矩阵相乘
#print(np.multiply(arr10, arr10))
print(arr10 * arr10)

# where 类似三元表达式
print(np.where(arr10 > 0, 1, -1)) #arr10的每个元素去做判断


[[-2. -1.  2.  1.  2.]
 [ 1.  2.  1. -0. -0.]
 [ 1. -3.  1.  1. -0.]]
[[-3. -2.  1.  0.  1.]
 [ 0.  1.  0. -1. -1.]
 [ 0. -4.  0.  0. -1.]]
[[-2. -1.  1.  0.  1.]
 [ 0.  1.  1. -1. -1.]
 [ 0. -3.  1.  1. -1.]]
[[2.05350225 1.30746331 1.26118858 0.47843432 1.16760753]
 [0.40092568 1.34853534 0.8970547  0.98781217 0.79653315]
 [0.38773733 3.25536926 0.55567805 0.74809271 0.83242683]]
[[ 4.2168715   1.7094603   1.59059664  0.2288994   1.36330735]
 [ 0.1607414   1.81854757  0.80470714  0.97577289  0.63446506]
 [ 0.15034024 10.59742899  0.30877809  0.55964271  0.69293443]]
[[-1 -1  1  1  1]
 [ 1  1  1 -1 -1]
 [ 1 -1  1  1 -1]]


In [99]:
# 内置函数
arr11 = np.arange(12).reshape(3,4)
print(arr11)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [103]:
# 求平均值
print(np.mean(arr11))
# 求元素的和
print(np.sum(arr11))
# 按 列 统计和 返回一维数组
print(np.sum(arr11,axis=0))
# 按 行 统计和 返回一维数组
print(np.sum(arr11,axis=1))

print(np.cumsum(arr11))

5.5
66
[12 15 18 21]
[ 6 22 38]
[ 0  1  3  6 10 15 21 28 36 45 55 66]


### 去重/排序函数

In [105]:
arr13 = np.array([[1,2,1],[2,3,5]])
print(arr13)

[[1 2 1]
 [2 3 5]]


In [106]:
#去重
arr14 = np.unique(arr13)
print(arr13)
print(arr14)

[[1 2 1]
 [2 3 5]]
[1 2 3 5]


In [108]:
# 排序定义数组
arr15 = np.array([1,2,1,6,5,3])
print(arr15)

[1 2 1 6 5 3]


In [110]:
#排序
arr16 = np.sort(arr15)
print(arr15)
print(arr16)

#通过数组对象.sort() 直接修改原数组
arr15.sort()
print(arr15)

[1 2 1 6 5 3]
[1 1 2 3 5 6]
[1 1 2 3 5 6]


# 矩阵运算

### 加法运算

In [115]:
# 定义数组
arr20 = np.array([10,20,30,40])
arr21 = np.arange(4)

print(arr20)
print(arr21)

[10 20 30 40]
[0 1 2 3]


In [116]:
# 减法  对应元素做减法运算
print(arr20 - arr21)

[10 19 28 37]


In [117]:
# 加法
print(arr20 + arr21)

[10 21 32 43]


### 矩阵乘法

In [118]:
# 定义数组
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [125]:
# 矩阵元素乘法(哈达玛积)  行列数一致(对应坐标的元素做乘法)
print(arr1 * arr2)
print(np.multiply(arr1,arr2))

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [121]:
# 矩阵乘法  行列数不一致
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[9,8],[6,5],[3,2]])
print(arr3)
print(arr4)

[[1 2 3]
 [4 5 6]]
[[9 8]
 [6 5]
 [3 2]]


In [124]:
# 矩阵乘法(线代)
# 第一个矩阵的列 = 第二个矩阵的行
# A列 = B行  结果是 A行B列
print(np.dot(arr3,arr4))

print(arr3.dot(arr4))

#语法糖
print(arr3 @ arr4)

[[30 24]
 [84 69]]
[[30 24]
 [84 69]]
[[30 24]
 [84 69]]
