# pandas

In [2]:
import pandas as pd
import numpy as np

### pandas两大核心对象
#### series 一列数据     DataFrame 多列数据

In [ ]:
# 创建series对象  默认自增索引
s1 = pd.Series([1,2,3,4,5,6])
print(s1)

In [ ]:
# 创建series对象  自定义索引
s2 = pd.Series([1,2,3,4,5,6],index=['a',11,13,14,15,18])
print(s2)

In [ ]:
# 使用元组创建Series对象
s3 = pd.Series((2,4,6,8,10))
print(s3)

In [ ]:
# 使用字典创建Series对象
s4 = pd.Series({'a':2,'b':3,'c':5,'d':8})
print(s4)

In [ ]:
# 使用numpy创建Series对象
s5 = pd.Series(np.arange(5))
print(s5)

In [ ]:
s6 = pd.Series(data=[i for i in range(6)],index=[i for i in 'ABCDEF'])
print(s6)

In [12]:
# 获取Series对象的索引值
print(s6.index)

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')


In [13]:
# 获取Series对象的值
print(s6.values)

[0 1 2 3 4 5]


In [15]:
# 获取Series对象的 索引对应的元素
print(s6['F'])

# 根据索引修改Series对象的元素值
s6['F'] = 100

print(s6)

5
A      0
B      1
C      2
D      3
E      4
F    100
dtype: int64


# DataFrame 对象

In [5]:
# 创建dataframe
# 字典 + 列表
# 每个键值对 = 1列数据
data = {
    'name':['迪丽热巴', '古力娜扎', '马儿扎哈', '易烊千玺'],
    'gender':['女', '女', '女', '男'],
    'age':[18, 19, 20, 21]
}

# 封装
df1 = pd.DataFrame(data)

print(df1)

   name gender  age
0  迪丽热巴      女   18
1  古力娜扎      女   19
2  马儿扎哈      女   20
3  易烊千玺      男   21


In [8]:
# 列表 +元组/列表 创建 df对象
# 每个键值对 = 1行数据  字典默认是索引
data = [
    ('迪丽热巴','女',18),
    ('古力娜扎','女',19),
    ('马儿扎哈','女',20),
    ('易烊千玺','男',21)
]

df2 = pd.DataFrame(data,columns=['name','gender','age'])

df2

,name,gender,age
0,迪丽热巴,女,18
1,古力娜扎,女,19
2,马儿扎哈,女,20
3,易烊千玺,男,21


#### numpy的ndarray-->pandas DataFrame

In [9]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
df3 = pd.DataFrame(arr1,columns=['a','b','c','d'])
df3

,a,b,c,d
0,0,1,2,3
1,4,5,6,7
2,8,9,10,11


#### 学生信息处理案例

In [18]:
# 10名同学 5门功课  成绩范围40-100
# 生成10行5列  的 40-100范围的数据
score_df = pd.DataFrame(np.random.randint(40,101,(10,5)))
score_df

,0,1,2,3,4
0,68,76,91,46,80
1,50,75,64,56,57
2,56,82,49,97,51
3,50,96,53,97,78
4,91,40,40,89,44
5,69,65,94,60,59
6,85,80,82,62,47
7,73,67,74,56,49
8,99,96,68,82,90
9,72,74,85,84,100


In [20]:
# 修改DataFarme对象的 列名 和 索引列值
column_names = ['数学','语文','英语','政治','体育']
index_names = ['同学'+str(i) for i in range(score_df.shape[0])]
print(index_names)
# score_df.columns = column_names
# score_df.index=index_names

score_df.rename(
    index={i:index_names[i] for i in range(score_df.shape[0])},
    columns={i:column_names[i] for i in range(score_df.shape[1])},
    inplace=True
)

score_df

['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']


,数学,语文,英语,政治,体育
同学0,68,76,91,46,80
同学1,50,75,64,56,57
同学2,56,82,49,97,51
同学3,50,96,53,97,78
同学4,91,40,40,89,44
同学5,69,65,94,60,59
同学6,85,80,82,62,47
同学7,73,67,74,56,49
同学8,99,96,68,82,90
同学9,72,74,85,84,100


#### DataFrame基本属性

In [24]:
# shape 维度（行列数）
print(score_df.shape)

print(score_df.index)
print(score_df.columns)

print(score_df.values)

(10, 5)
Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='str')
Index(['数学', '语文', '英语', '政治', '体育'], dtype='str')
[[ 68  76  91  46  80]
 [ 50  75  64  56  57]
 [ 56  82  49  97  51]
 [ 50  96  53  97  78]
 [ 91  40  40  89  44]
 [ 69  65  94  60  59]
 [ 85  80  82  62  47]
 [ 73  67  74  56  49]
 [ 99  96  68  82  90]
 [ 72  74  85  84 100]]


In [26]:
# 行列转置
score_df.T

,同学0,同学1,同学2,同学3,同学4,同学5,同学6,同学7,同学8,同学9
数学,68,50,56,50,91,69,85,73,99,72
语文,76,75,82,96,40,65,80,67,96,74
英语,91,64,49,53,40,94,82,74,68,85
政治,46,56,97,97,89,60,62,56,82,84
体育,80,57,51,78,44,59,47,49,90,100


#### DataFrame基本属性

In [27]:
score_df

,数学,语文,英语,政治,体育
同学0,68,76,91,46,80
同学1,50,75,64,56,57
同学2,56,82,49,97,51
同学3,50,96,53,97,78
同学4,91,40,40,89,44
同学5,69,65,94,60,59
同学6,85,80,82,62,47
同学7,73,67,74,56,49
同学8,99,96,68,82,90
同学9,72,74,85,84,100


In [29]:
#默认前5行
#score_df.head()
score_df.head(3)

#从后往前拿数据
#score_df.tail()

,数学,语文,英语,政治,体育
同学0,68,76,91,46,80
同学1,50,75,64,56,57
同学2,56,82,49,97,51


In [30]:
# df对象的详细信息
score_df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 同学0 to 同学9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   数学      10 non-null     int32
 1   语文      10 non-null     int32
 2   英语      10 non-null     int32
 3   政治      10 non-null     int32
 4   体育      10 non-null     int32
dtypes: int32(5)
memory usage: 580.0+ bytes


In [31]:
# 统计信息
score_df.describe()


,数学,语文,英语,政治,体育
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,71.300000,75.100000,70.000000,72.900000,65.500000
std,16.680328,16.148271,18.475209,18.876499,19.884388
min,50.000000,40.000000,40.000000,46.000000,44.000000
25%,59.000000,68.750000,55.750000,57.000000,49.500000
50%,70.500000,75.500000,71.000000,72.000000,58.000000
75%,82.000000,81.500000,84.250000,87.750000,79.500000
max,99.000000,96.000000,94.000000,97.000000,100.000000


In [33]:
# 重置索引列
# 默认 drop = False
score_df.reset_index(drop = True)

,数学,语文,英语,政治,体育
0,68,76,91,46,80
1,50,75,64,56,57
2,56,82,49,97,51
3,50,96,53,97,78
4,91,40,40,89,44
5,69,65,94,60,59
6,85,80,82,62,47
7,73,67,74,56,49
8,99,96,68,82,90
9,72,74,85,84,100


In [34]:
# 重新设置索引
score_df.set_index(['语文','数学'])

,,英语,政治,体育
语文,数学,,,
76,68,91,46,80
75,50,64,56,57
82,56,49,97,51
96,50,53,97,78
40,91,40,89,44
65,69,94,60,59
80,85,82,62,47
67,73,74,56,49
96,99,68,82,90
